In [5]:
import pandas as pd
import numpy as np
import warnings; warnings.simplefilter('ignore')
Img = pd.read_csv("G:/Data/Cases/Image Segmentation/Image_Segmention.csv")
from sklearn.preprocessing import LabelEncoder
lbcode = LabelEncoder()
Img['Class']=lbcode.fit_transform(Img['Class'])
Img.head()

Class  region.centroid.col  region.centroid.row  region.pixel.count  \
0      0                  188                  133                   9   
1      0                  105                  139                   9   
2      0                   34                  137                   9   
3      0                   39                  111                   9   
4      0                   16                  128                   9   

   short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                   0.0                   0.0    0.333333  0.266667   
1                   0.0                   0.0    0.277778  0.107407   
2                   0.0                   0.0    0.500000  0.166667   
3                   0.0                   0.0    0.722222  0.374074   
4                   0.0                   0.0    0.500000  0.077778   

   hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0    0.500000  0.077778        6.666666     8.333334      7.777778   
1    0.833333  0.522222        6.111111     7.555555      7.222222   
2    1.111111  0.474074        5.851852     7.777778      6.444445   
3    0.888889  0.429629        6.037037     7.000000      7.666666   
4    0.666667  0.311111        5.555555     6.888889      6.666666   

   rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0       3.888889    5.000000     3.333333     -8.333333    8.444445   
1       3.555556    4.333334     3.333333     -7.666666    7.555555   
2       3.333333    5.777778     1.777778     -7.555555    7.777778   
3       3.444444    2.888889     4.888889     -7.777778    7.888889   
4       3.111111    4.000000     3.333333     -7.333334    7.111111   

   saturation.mean  hue-mean  
0         0.538580 -0.924817  
1         0.532628 -0.965946  
2         0.573633 -0.744272  
3         0.562919 -1.175773  
4         0.561508 -0.985811

In [6]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import classification_report, accuracy_score
from sklearn.neural_network import MLPClassifier

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X=Img.iloc[:,1:]
y=Img.iloc[:,0]

In [7]:
# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.3, 
                                                    random_state=2019,
                                                    stratify=y)

mlp = MLPClassifier(hidden_layer_sizes=(3,3,2),random_state=2019)
mlp.fit( X_train , y_train )
y_pred = mlp.predict(X_test)

In [8]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
y_pred_prob = mlp.predict_proba(X_test)[:,1]


[[0 0 9 0 0 0 0]
 [0 0 8 0 0 0 1]
 [0 0 9 0 0 0 0]
 [0 0 9 0 0 0 0]
 [0 0 3 0 0 0 6]
 [0 0 0 0 0 0 9]
 [0 0 5 0 0 1 3]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.00      0.00      0.00         9
           2       0.21      1.00      0.35         9
           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         9
           6       0.16      0.33      0.21         9

   micro avg       0.19      0.19      0.19        63
   macro avg       0.05      0.19      0.08        63
weighted avg       0.05      0.19      0.08        63

0.19047619047619047
